version: '3.8'
services:
    app:
        build: .
        image: smmshz34/autoclicker:latest
        network_mode: host
        environment:
            PYTHONUNBUFFERED: 1
            api_id: #your api id
            api_hash: #your api hash
            sessionString: #your telethon session string
            admin: #your telegram id
            tapswap_clicker: on,
            hamster_clicker: on,
            cexio_clicker: on,
            auto_upgrade: true,
            max_days_for_return: 10,
            max_charge_level: 5,
            max_energy_level: 10,
            max_tap_level: 10,
            cexio_ref_code: 1716965343289920,
            version: 1.1.1
